// File generated by FlutterFire CLI.
// This file is not required if you're using Firebase hosting

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTH-PLACEHOLDER-KEY',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'suicide-hotline-app',
    authDomain: 'suicide-hotline-app.firebaseapp.com',
    storageBucket: 'suicide-hotline-app.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEF-PLACEHOLDER-KEY-ANDROID',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'suicide-hotline-app',
    storageBucket: 'suicide-hotline-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyGHI-PLACEHOLDER-KEY-IOS',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'suicide-hotline-app',
    storageBucket: 'suicide-hotline-app.appspot.com',
    iosClientId: 'PLACEHOLDER-IOS-CLIENT-ID',
    iosBundleId: 'com.example.suicideHotlineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyXYZ-PLACEHOLDER-KEY-MACOS',
    appId: '1:123456789012:ios:abcdefg1234567890',
    messagingSenderId: '123456789012',
    projectId: 'suicide-hotline-app',
    storageBucket: 'suicide-hotline-app.appspot.com',
    iosClientId: 'PLACEHOLDER-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.suicideHotlineApp',
  );
} 